import type {
  GuidedLabMission,
  GuidedLabMissionPresentation,
  SandboxLabMission,
  SandboxLabMissionPresentation,
  Scenario,
} from "@learn-loop/core";

export const classifyMixturesScenario: Scenario = {
  id: "classify-mixtures",
  title: "Classify the Mixture",
  concept: "Exploring Mixtures — solutions, suspensions, and colloids",
  grade: 6,
  entities: [
    { id: "salt-solution", label: "Salt water", color: "#b7d7ee", kind: "solution", solubility: "soluble" },
    { id: "chalk-suspension", label: "Chalk water", color: "#d6d2c6", kind: "suspension", solubility: "insoluble" },
    { id: "milk-colloid", label: "Milk in water", color: "#f4efe4", kind: "colloid", solubility: "soluble" },
    { id: "clear-beam", label: "Clear path", color: "#b7d7ee", kind: "observation" },
    { id: "scattered-beam", label: "Scattered beam", color: "#fff0a6", kind: "observation" },
    { id: "settled-chalk", label: "Settled chalk", color: "#b8aa96", kind: "sediment", solubility: "insoluble" },
    { id: "chalk-residue", label: "Chalk residue", color: "#c9c3b7", kind: "solid", solubility: "insoluble" },
  ],
  shelf: ["salt-solution", "chalk-suspension", "milk-colloid"],
  stations: {
    testTube: { contents: [], color: "#dfe9f5", heat: "room", phase: "empty" },
    residue: { contents: [], color: "#f0f2f4", heat: "room", phase: "empty" },
    filtrate: { contents: [], color: "#dfe9f5", heat: "room", phase: "empty" },
  },
  rules: [
    {
      id: "load-milk",
      on: "pour",
      requires: ["milk-colloid"],
      transform: {
        kind: "react",
        consume: [],
        produce: [],
        newColor: "#f4efe4",
      },
      observation: "The liquid looks cloudy and uniform.",
      explanation: "Milk in water is a colloid: the particles stay spread out but are large enough to affect light.",
    },
    {
      id: "milk-tyndall",
      on: "shineLight",
      requires: ["milk-colloid"],
      transform: {
        kind: "react",
        consume: [],
        produce: ["scattered-beam"],
        newColor: "#fff1ba",
      },
      observation: "The beam becomes visible through the cloudy liquid.",
      explanation: "Colloid particles scatter light, which is the Tyndall effect.",
    },
    {
      id: "load-chalk",
      on: "pour",
      requires: ["chalk-suspension"],
      transform: {
        kind: "react",
        consume: [],
        produce: [],
        newColor: "#d6d2c6",
      },
      observation: "The chalk makes a cloudy mixture with visible solid particles.",
      explanation: "Chalk does not dissolve in water, so it forms a suspension.",
    },
    {
      id: "chalk-settles",
      on: "wait",
      requires: ["chalk-suspension"],
      transform: {
        kind: "react",
        consume: [],
        produce: ["settled-chalk"],
        newColor: "#c9d8de",
      },
      observation: "A chalky layer settles at the bottom.",
      explanation: "Suspension particles are large enough to settle when left undisturbed.",
    },
    {
      id: "filter-chalk",
      on: "filter",
      at: "source",
      requires: ["chalk-suspension"],
      transform: {
        kind: "split",
        solidTo: "residue",
        liquidTo: "filtrate",
      },
      observation: "Chalk stays on the filter paper while clearer water passes through.",
      explanation: "Filtration works for many suspensions because the insoluble particles are trapped by the filter.",
    },
  ],
  steps: [
    {
      id: "add-milk",
      predictPrompt: "Which sample should reveal the Tyndall effect?",
      options: [
        { label: "Milk in water", correct: true, feedback: "Yes. A colloid scatters light." },
        { label: "Salt water", correct: false, feedback: "A true solution usually does not show the beam." },
      ],
      goal: "Prepare the colloid sample.",
      hints: {
        shineLight: "Put the sample in the tube before testing it with light.",
        wait: "Settling is more useful for suspensions than colloids.",
      },
      actionPrompt: "Pour milk in water into the test tube.",
      expect: { type: "pour", reagent: "milk-colloid", target: "testTube" },
      explanation: "Milk in water is a colloid, so it stays cloudy without quickly settling.",
    },
    {
      id: "light-milk",
      predictPrompt: "What will happen when light passes through the colloid?",
      options: [
        { label: "The beam becomes visible", correct: true, feedback: "Correct. Colloids scatter light." },
        { label: "The beam disappears completely", correct: false, feedback: "The beam is visible because it scatters." },
      ],
      goal: "Test the cloudy sample with a light beam.",
      hints: {
        pour: "The sample is ready. Now test how it handles light.",
        filter: "Filtering is not the observation this step asks for.",
      },
      actionPrompt: "Shine a light through the sample.",
      expect: { type: "shineLight", target: "testTube" },
      explanation: "The visible beam is the Tyndall effect, caused by colloid particles scattering light.",
    },
    {
      id: "load-chalk",
      predictPrompt: "Which sample should settle on standing?",
      options: [
        { label: "Chalk water", correct: true, feedback: "Yes. It is a suspension." },
        { label: "Salt water", correct: false, feedback: "Salt dissolves and does not settle like chalk." },
      ],
      goal: "Prepare a suspension sample.",
      hints: {
        shineLight: "First place the suspension in the tube.",
        filter: "Filtering comes after the suspension is prepared.",
      },
      actionPrompt: "Pour chalk water into the test tube.",
      expect: { type: "pour", reagent: "chalk-suspension", target: "testTube" },
      explanation: "Chalk water is a suspension because insoluble solid particles remain dispersed.",
    },
    {
      id: "settle-chalk",
      predictPrompt: "What should happen after the suspension stands?",
      options: [
        { label: "Chalk settles", correct: true, feedback: "Correct. The particles are large enough to settle." },
        { label: "It becomes a true solution", correct: false, feedback: "Waiting cannot dissolve insoluble chalk." },
      ],
      goal: "Let the suspension stand and observe settling.",
      hints: {
        shineLight: "Light can show scattering, but this step asks about settling.",
        heat: "Heating is not needed to classify this suspension.",
      },
      actionPrompt: "Wait for the suspension to settle.",
      expect: { type: "wait", target: "testTube" },
      explanation: "Large suspension particles settle under gravity, unlike particles in true solutions.",
    },
    {
      id: "filter-chalk",
      predictPrompt: "Can filtration remove chalk particles?",
      options: [
        { label: "Yes", correct: true, feedback: "Correct. Insoluble chalk remains as residue." },
        { label: "No", correct: false, feedback: "Filtration can trap these large insoluble particles." },
      ],
      goal: "Separate the suspension by filtration.",
      hints: {
        wait: "The chalk has already settled; use the method that separates solid from liquid.",
        heat: "Boiling is not required for this classification test.",
      },
      actionPrompt: "Filter the test tube contents.",
      expect: { type: "filter", source: "testTube" },
      explanation: "The chalk residue remains on the filter paper while the liquid passes through.",
    },
  ],
};

export const saltSandScenario: Scenario = {
  id: "salt-sand",
  title: "Separate Salt and Sand",
  concept: "Separation — solubility, filtration, and evaporation",
  grade: 6,
  entities: [
    { id: "salt", label: "Salt", color: "#f7f0dc", kind: "salt", solubility: "soluble" },
    { id: "sand", label: "Sand", color: "#c8aa72", kind: "solid", solubility: "insoluble" },
    { id: "water", label: "Water", color: "#9bd0f0", kind: "solvent", solubility: "soluble" },
    { id: "water-vapour", label: "Water vapour", color: "#d8ecf8", kind: "vapour" },
  ],
  shelf: ["water"],
  stations: {
    beaker: { contents: ["salt", "sand"], color: "#c8aa72", heat: "room", phase: "solid" },
    residue: { contents: [], color: "#f0f2f4", heat: "room", phase: "empty" },
    filtrate: { contents: [], color: "#dfe9f5", heat: "room", phase: "empty" },
  },
  rules: [
    {
      id: "dissolve-salt",
      on: "pour",
      requires: ["salt", "sand", "water"],
      transform: {
        kind: "react",
        consume: [],
        produce: [],
        newColor: "#d5cab1",
      },
      observation: "Salt dissolves in the water while sand remains gritty.",
      explanation: "Water dissolves salt but not sand, giving the two solids different behaviours.",
    },
    {
      id: "filter-sand",
      on: "filter",
      at: "source",
      requires: ["salt", "sand", "water"],
      transform: {
        kind: "split",
        solidTo: "residue",
        liquidTo: "filtrate",
      },
      observation: "Sand is trapped as residue; salt water passes into the filtrate.",
      explanation: "Filtration separates insoluble sand from the salt solution.",
    },
    {
      id: "evaporate-salt",
      on: "heat",
      requires: ["salt", "water"],
      transform: {
        kind: "evaporate",
        leaves: ["salt"],
        emits: ["water-vapour"],
        newColor: "#f7f0dc",
        heat: "hot",
      },
      observation: "Water vapour rises and salt crystals remain.",
      explanation: "Evaporation removes the solvent and leaves the dissolved salt behind.",
    },
  ],
  steps: [
    {
      id: "add-water",
      predictPrompt: "What should dissolve first?",
      options: [
        { label: "Salt dissolves", correct: true, feedback: "Correct. Salt is soluble in water." },
        { label: "Sand dissolves", correct: false, feedback: "Sand is insoluble in water." },
      ],
      goal: "Use solubility to make only one solid dissolve.",
      hints: {
        filter: "Filtering before dissolving would leave both solids together.",
        heat: "Heat is useful after the sand has been removed.",
      },
      actionPrompt: "Add water to the salt-sand mixture.",
      expect: { type: "pour", reagent: "water", target: "beaker" },
      explanation: "Salt dissolves in water while sand stays insoluble.",
    },
    {
      id: "filter",
      predictPrompt: "What will stay on the filter?",
      options: [
        { label: "Sand", correct: true, feedback: "Correct. Insoluble sand is residue." },
        { label: "Salt solution", correct: false, feedback: "The salt solution passes through as filtrate." },
      ],
      goal: "Remove the insoluble sand.",
      hints: {
        pour: "The mixture is already wet. Now separate solid from liquid.",
        heat: "Heating now would leave sand mixed with salt again.",
      },
      actionPrompt: "Filter the beaker.",
      expect: { type: "filter", source: "beaker" },
      explanation: "Filter paper traps the sand and lets the dissolved salt pass with water.",
    },
    {
      id: "evaporate",
      predictPrompt: "How do you recover the dissolved salt?",
      options: [
        { label: "Evaporate water", correct: true, feedback: "Correct. Salt remains after water leaves." },
        { label: "Filter again", correct: false, feedback: "Dissolved salt passes through filters." },
      ],
      goal: "Recover salt crystals from the filtrate.",
      hints: {
        filter: "The sand is already removed; filtering cannot catch dissolved salt.",
        pour: "Adding more liquid moves away from recovering the solid.",
      },
      actionPrompt: "Heat the filtrate.",
      expect: { type: "heat", target: "filtrate" },
      explanation: "Heating evaporates water, leaving salt crystals behind.",
    },
  ],
};

export const crystallizationScenario: Scenario = {
  id: "crystallization",
  title: "Grow Pure Crystals",
  concept: "Separation — crystallization from a hot saturated solution",
  grade: 6,
  entities: [
    { id: "copper-sulfate", label: "Copper sulfate", color: "#2f8fce", kind: "solute", solubility: "soluble" },
    { id: "impurity", label: "Dust impurity", color: "#7b7568", kind: "solid", solubility: "insoluble" },
    { id: "water", label: "Water", color: "#9bd0f0", kind: "solvent", solubility: "soluble" },
    { id: "crystals", label: "Blue crystals", color: "#1976bd", kind: "crystal", solubility: "soluble" },
  ],
  shelf: ["water"],
  stations: {
    dish: { contents: ["copper-sulfate", "impurity"], color: "#7d8fa3", heat: "room", phase: "solid" },
    residue: { contents: [], color: "#f0f2f4", heat: "room", phase: "empty" },
    filtrate: { contents: [], color: "#dfe9f5", heat: "room", phase: "empty" },
  },
  rules: [
    {
      id: "make-solution",
      on: "pour",
      requires: ["copper-sulfate", "impurity", "water"],
      transform: {
        kind: "react",
        consume: [],
        produce: [],
        newColor: "#1f9ad6",
      },
      observation: "The copper sulfate dissolves into a bright blue solution; dust remains.",
      explanation: "The useful solute dissolves, while insoluble impurities can still be removed.",
    },
    {
      id: "hot-solution",
      on: "heat",
      requires: ["copper-sulfate", "water"],
      transform: {
        kind: "react",
        consume: [],
        produce: [],
        newColor: "#117fbd",
        heat: "hot",
      },
      observation: "The solution becomes hot and deeper blue.",
      explanation: "A hot solution can hold more solute and prepares a saturated solution for crystallization.",
    },
    {
      id: "remove-impurity",
      on: "filter",
      at: "source",
      requires: ["copper-sulfate", "water", "impurity"],
      transform: {
        kind: "split",
        solidTo: "residue",
        liquidTo: "filtrate",
      },
      observation: "Dust stays on the filter; blue solution passes through.",
      explanation: "Hot filtration removes insoluble impurities before crystals form.",
    },
    {
      id: "cool-crystals",
      on: "cool",
      requires: ["copper-sulfate", "water"],
      transform: {
        kind: "react",
        consume: ["copper-sulfate"],
        produce: ["crystals"],
        newColor: "#c7e5f4",
        heat: "cool",
      },
      observation: "Blue crystals grow as the clear solution cools.",
      explanation: "Cooling lowers solubility, so excess copper sulfate separates as crystals.",
    },
  ],
  steps: [
    {
      id: "dissolve",
      predictPrompt: "What should water do to copper sulfate?",
      options: [
        { label: "Dissolve it", correct: true, feedback: "Correct. It forms a blue solution." },
        { label: "Turn it into vapour", correct: false, feedback: "Water is the solvent here." },
      ],
      goal: "Make a blue copper sulfate solution.",
      hints: {
        filter: "Filter after the soluble material is in solution.",
        cool: "Cooling before making the solution will not grow crystals.",
      },
      actionPrompt: "Add water to the dish.",
      expect: { type: "pour", reagent: "water", target: "dish" },
      explanation: "Copper sulfate dissolves in water, while dust remains insoluble.",
    },
    {
      id: "heat",
      predictPrompt: "Why heat the solution?",
      options: [
        { label: "To prepare a hot saturated solution", correct: true, feedback: "Correct." },
        { label: "To filter the crystals", correct: false, feedback: "Crystals form after cooling." },
      ],
      goal: "Heat the solution before filtering.",
      hints: {
        filter: "The chapter prepares a hot solution before slow cooling.",
        cool: "Cooling comes after the hot solution has been cleaned.",
      },
      actionPrompt: "Heat the dish.",
      expect: { type: "heat", target: "dish" },
      explanation: "Heating helps prepare the concentrated solution used for crystallization.",
    },
    {
      id: "filter-hot",
      predictPrompt: "What does hot filtration remove?",
      options: [
        { label: "Insoluble impurities", correct: true, feedback: "Correct." },
        { label: "The dissolved copper sulfate", correct: false, feedback: "Dissolved solute passes with the filtrate." },
      ],
      goal: "Remove the insoluble impurity.",
      hints: {
        cool: "Cooling too early can trap impurities in the crystals.",
        heat: "The solution is already hot enough.",
      },
      actionPrompt: "Filter the hot solution.",
      expect: { type: "filter", source: "dish" },
      explanation: "Filtering removes insoluble dust while copper sulfate remains in solution.",
    },
    {
      id: "cool",
      predictPrompt: "What forms when the hot solution cools slowly?",
      options: [
        { label: "Crystals", correct: true, feedback: "Correct. The solute separates in ordered crystals." },
        { label: "Sand", correct: false, feedback: "No sand is present in this mission." },
      ],
      goal: "Cool the clean solution to grow crystals.",
      hints: {
        filter: "The impurity is already removed.",
        heat: "More heating keeps the solute dissolved.",
      },
      actionPrompt: "Cool the filtrate.",
      expect: { type: "cool", target: "filtrate" },
      explanation: "As the hot solution cools, solubility falls and pure crystals grow.",
    },
  ],
};

export const distillationScenario: Scenario = {
  id: "distillation",
  title: "Recover Both Liquids",
  concept: "Separation — distillation by boiling point",
  grade: 6,
  entities: [
    { id: "acetone", label: "Acetone", color: "#d7f0ff", kind: "liquid", solubility: "soluble" },
    { id: "water", label: "Water", color: "#9bd0f0", kind: "liquid", solubility: "soluble" },
  ],
  shelf: [],
  stations: {
    flask: { contents: ["acetone", "water"], color: "#b9d9e9", heat: "room", phase: "solution" },
    acetoneReceiver: { contents: [], color: "#eef7fb", heat: "room", phase: "empty" },
    waterReceiver: { contents: [], color: "#eef7fb", heat: "room", phase: "empty" },
  },
  rules: [
    {
      id: "distil-acetone",
      on: "heat",
      requires: ["acetone", "water"],
      transform: {
        kind: "distil",
        volatile: ["acetone"],
        collectTo: "acetoneReceiver",
        collectColor: "#d7f0ff",
        newColor: "#9bd0f0",
        heat: "hot",
      },
      observation: "Acetone vapour condenses first in the receiver.",
      explanation: "Acetone boils at about 56°C, lower than water, so it distils first.",
    },
    {
      id: "distil-water",
      on: "heat",
      requires: ["water"],
      transform: {
        kind: "distil",
        volatile: ["water"],
        collectTo: "waterReceiver",
        collectColor: "#9bd0f0",
        newColor: "#f0f2f4",
        heat: "hot",
      },
      observation: "The remaining water distils into the second receiver.",
      explanation: "After acetone is removed, continued heating can recover water separately.",
    },
  ],
  steps: [
    {
      id: "recover-acetone",
      predictPrompt: "Which liquid should distil first?",
      options: [
        { label: "Acetone", correct: true, feedback: "Correct. It has the lower boiling point." },
        { label: "Water", correct: false, feedback: "Water boils at a higher temperature." },
      ],
      goal: "Recover the lower-boiling liquid first.",
      hints: {
        filter: "Filtration cannot separate two miscible liquids.",
        pour: "No extra reagent is needed for distillation.",
      },
      actionPrompt: "Heat the distillation flask.",
      expect: { type: "heat", target: "flask" },
      explanation: "The lower-boiling acetone vaporizes and condenses before water.",
    },
    {
      id: "recover-water",
      predictPrompt: "What remains after acetone leaves?",
      options: [
        { label: "Water", correct: true, feedback: "Correct. It can be recovered by continued heating." },
        { label: "Sand", correct: false, feedback: "This mixture contains two miscible liquids." },
      ],
      goal: "Recover the remaining liquid.",
      hints: {
        filter: "There is no insoluble solid to trap.",
        cool: "Cooling alone will not move the remaining water into the receiver.",
      },
      actionPrompt: "Heat the flask again.",
      expect: { type: "heat", target: "flask" },
      explanation: "Once acetone is gone, water can distil into its own receiver.",
    },
  ],
};

export const chromatographyScenario: Scenario = {
  id: "chromatography",
  title: "Ink Detective",
  concept: "Separation — paper chromatography",
  grade: 6,
  entities: [
    { id: "black-ink", label: "Black ink", color: "#28313b", kind: "mixture", solubility: "soluble" },
    { id: "water", label: "Water", color: "#9bd0f0", kind: "solvent", solubility: "soluble" },
    { id: "pigment-bands", label: "Pigment bands", color: "#d86f45", kind: "observation", solubility: "soluble" },
  ],
  shelf: ["black-ink", "water"],
  stations: {
    paper: { contents: [], color: "#f4efe2", heat: "room", phase: "solid" },
  },
  rules: [
    {
      id: "spot-ink",
      on: "pour",
      requires: ["black-ink"],
      transform: {
        kind: "react",
        consume: [],
        produce: [],
        newColor: "#32363d",
      },
      observation: "A dark ink spot sits near the bottom of the paper.",
      explanation: "A small spot lets the solvent carry the ink components upward.",
    },
    {
      id: "add-solvent",
      on: "pour",
      requires: ["water"],
      transform: {
        kind: "react",
        consume: [],
        produce: [],
        newColor: "#9bd0f0",
      },
      observation: "Water wets the lower edge of the paper below the ink spot.",
      explanation: "The solvent must touch the paper below the spot so it can rise by capillary action.",
    },
    {
      id: "run-chromatography",
      on: "chromatograph",
      requires: ["black-ink", "water"],
      transform: {
        kind: "react",
        consume: [],
        produce: ["pigment-bands"],
        newColor: "#f4efe2",
      },
      observation: "The black ink separates into coloured bands.",
      explanation: "Different pigments travel different distances with the solvent, so they separate on the paper.",
    },
  ],
  steps: [
    {
      id: "spot",
      predictPrompt: "Where does the ink begin?",
      options: [
        { label: "As a small spot on paper", correct: true, feedback: "Correct." },
        { label: "Mixed through the whole cup", correct: false, feedback: "The paper needs a small starting spot." },
      ],
      goal: "Place a small ink spot on the paper.",
      hints: {
        chromatograph: "The paper needs ink and solvent before the run can start.",
        heat: "Chromatography does not need heating.",
      },
      actionPrompt: "Add black ink to the paper.",
      expect: { type: "pour", reagent: "black-ink", target: "paper" },
      explanation: "A concentrated spot gives the pigments a common starting point.",
    },
    {
      id: "solvent",
      predictPrompt: "What carries the pigments upward?",
      options: [
        { label: "Water solvent", correct: true, feedback: "Correct." },
        { label: "Filter paper alone", correct: false, feedback: "The solvent moves through the paper and carries pigments." },
      ],
      goal: "Add solvent below the ink spot.",
      hints: {
        chromatograph: "The solvent cup is empty. Add solvent before running the paper.",
        filter: "This test separates dissolved pigments, not an insoluble solid.",
      },
      actionPrompt: "Add water to the chromatography paper.",
      expect: { type: "pour", reagent: "water", target: "paper" },
      explanation: "Water rises through the paper and carries soluble pigments with it.",
    },
    {
      id: "separate",
      predictPrompt: "Why do bands appear?",
      options: [
        { label: "Pigments travel differently", correct: true, feedback: "Correct." },
        { label: "The ink burns", correct: false, feedback: "No heating happens in paper chromatography." },
      ],
      goal: "Run chromatography and reveal hidden pigments.",
      hints: {
        heat: "Heating would damage the test; run chromatography instead.",
        wait: "Waiting alone is not the guided lab method here.",
      },
      actionPrompt: "Run the chromatography test.",
      expect: { type: "chromatograph", target: "paper" },
      explanation: "The solvent carries the pigments at different rates, separating the ink into bands.",
    },
  ],
};

export const missions: readonly Scenario[] = [
  classifyMixturesScenario,
  saltSandScenario,
  crystallizationScenario,
  distillationScenario,
  chromatographyScenario,
];

export const missionPresentations: readonly GuidedLabMissionPresentation[] = [
  {
    scenarioId: "classify-mixtures",
    badge: "Light + settling",
    stationVisuals: [
      {
        stationId: "testTube",
        kind: "test-tube",
        label: "Test tube",
        effectTags: ["scatter-light", "settle-particles"],
      },
      {
        stationId: "residue",
        kind: "filter",
        label: "Residue",
        effectTags: ["trap-residue"],
      },
      {
        stationId: "filtrate",
        kind: "receiver",
        label: "Filtrate",
      },
    ],
    completionMessage:
      "You used light, settling, and filtration to tell colloids and suspensions apart.",
  },
  {
    scenarioId: "salt-sand",
    badge: "Dissolve + filter",
    stationVisuals: [
      {
        stationId: "beaker",
        kind: "beaker",
        label: "Salt + sand",
      },
      {
        stationId: "residue",
        kind: "filter",
        label: "Sand residue",
        effectTags: ["trap-residue"],
      },
      {
        stationId: "filtrate",
        kind: "evaporating-dish",
        label: "Salt water",
        effectTags: ["grow-crystals", "vapour"],
      },
    ],
    completionMessage:
      "You dissolved salt, trapped sand, and recovered salt crystals by evaporation.",
  },
  {
    scenarioId: "crystallization",
    badge: "Crystal growth",
    stationVisuals: [
      {
        stationId: "dish",
        kind: "dish",
        label: "Impure solution",
        effectTags: ["distil-vapour"],
      },
      {
        stationId: "residue",
        kind: "filter",
        label: "Dust residue",
        effectTags: ["trap-residue"],
      },
      {
        stationId: "filtrate",
        kind: "dish",
        label: "Clean solution",
        effectTags: ["grow-crystals"],
      },
    ],
    completionMessage:
      "You cleaned the hot solution and cooled it to grow purer blue crystals.",
  },
  {
    scenarioId: "distillation",
    badge: "Boiling points",
    stationVisuals: [
      {
        stationId: "flask",
        kind: "distillation",
        label: "Distillation flask",
        effectTags: ["distil-vapour"],
      },
      {
        stationId: "acetoneReceiver",
        kind: "receiver",
        label: "Acetone",
      },
      {
        stationId: "waterReceiver",
        kind: "receiver",
        label: "Water",
      },
    ],
    completionMessage:
      "You recovered both liquids separately by using their different boiling points.",
  },
  {
    scenarioId: "chromatography",
    badge: "Hidden pigments",
    stationVisuals: [
      {
        stationId: "paper",
        kind: "paper",
        label: "Chromatography paper",
        effectTags: ["chromatography-bands"],
      },
    ],
    completionMessage:
      "You let the solvent carry ink pigments different distances to reveal the bands.",
  },
];

export const guidedLabMissions: readonly GuidedLabMission[] = missions.map(
  (scenario, index) => ({
    scenario,
    presentation: missionPresentations[index],
  }),
);

function feedbackCard(
  action: string,
  result: string,
  why: string,
  next: string,
  notebook: string,
) {
  return { action, result, why, next, notebook };
}

export const sandboxMissionPresentations: readonly SandboxLabMissionPresentation[] = [
  {
    scenarioId: "classify-mixtures",
    badge: "Cloudy or clear",
    question: "How can we tell cloudy mixtures apart?",
    materials: [
      { id: "testTube", label: "Test tube sample", stationId: "testTube" },
    ],
    tools: [
      { id: "add-milk", label: "Milk water", action: { type: "pour", reagent: "milk-colloid" } },
      { id: "add-chalk", label: "Chalk water", action: { type: "pour", reagent: "chalk-suspension" } },
      { id: "light", label: "Light", action: { type: "shineLight" } },
      { id: "wait", label: "Wait", action: { type: "wait" } },
      { id: "filter", label: "Filter", action: { type: "filter" } },
    ],
    interactions: [
      {
        id: "load-milk",
        materialId: "testTube",
        toolId: "add-milk",
        evidenceId: "cloudy-colloid",
        feedbackCard: feedbackCard(
          "You added milk water to the tube.",
          "The liquid turns cloudy but stays evenly mixed.",
          "The particles stay spread out instead of settling quickly.",
          "Shine light through the sample to test what the tiny particles do.",
          "Milk water stays evenly cloudy.",
        ),
        soundCue: "pour",
        reactionEffect: "dissolve",
        observation: "Milk water turns cloudy but stays evenly mixed.",
        explanation: "This is a colloid. The word matters after you see that the particles stay spread out.",
        effectTags: ["scatter-light"],
      },
      {
        id: "milk-light",
        materialId: "testTube",
        toolId: "light",
        evidenceId: "tyndall-visible",
        feedbackCard: feedbackCard(
          "You shined light through the cloudy milk water.",
          "The beam becomes visible inside the liquid.",
          "Tiny spread-out particles scatter light.",
          "Now compare it with chalk water.",
          "Milk water scatters light because tiny particles stay spread out.",
        ),
        soundCue: "light",
        reactionEffect: "light-scatter",
        observation: "The light beam shows up inside the cloudy milk water.",
        explanation: "Tiny spread-out particles scatter light. This is called the Tyndall effect.",
        effectTags: ["scatter-light"],
      },
      {
        id: "load-chalk",
        materialId: "testTube",
        toolId: "add-chalk",
        evidenceId: "chalk-suspension",
        feedbackCard: feedbackCard(
          "You added chalk water to the tube.",
          "Solid chalk floats through the water.",
          "Chalk does not dissolve like salt or sugar.",
          "Wait and see whether the solid stays spread out.",
          "Chalk water contains undissolved solid particles.",
        ),
        soundCue: "pour",
        reactionEffect: "settle",
        observation: "Chalk water looks cloudy because solid chalk is floating in it.",
        explanation: "Chalk does not dissolve. It makes a suspension.",
        effectTags: ["settle-particles"],
      },
      {
        id: "chalk-wait",
        materialId: "testTube",
        toolId: "wait",
        evidenceId: "chalk-settles",
        feedbackCard: feedbackCard(
          "You waited and watched the chalk water.",
          "Chalk grains sink toward the bottom.",
          "Large solid particles can settle when the mixture stands.",
          "Use the filter to see if those solids can be caught.",
          "Chalk particles settle when left standing.",
        ),
        soundCue: "wait",
        reactionEffect: "settle",
        observation: "The chalk grains sink and collect near the bottom.",
        explanation: "Large solid particles can settle when the mixture stands.",
        effectTags: ["settle-particles"],
      },
      {
        id: "chalk-filter",
        materialId: "testTube",
        toolId: "filter",
        evidenceId: "chalk-residue",
        feedbackCard: feedbackCard(
          "You filtered the chalk water.",
          "The filter catches chalk and clearer water passes through.",
          "A filter can trap solid particles that are too large to pass.",
          "Use this evidence to compare cloudy mixtures.",
          "Filtration catches undissolved chalk.",
        ),
        soundCue: "filter",
        reactionEffect: "filter-residue",
        observation: "The filter catches chalk. Clearer water passes through.",
        explanation: "Filtration works when solid particles are too large to pass through the filter.",
        effectTags: ["trap-residue"],
      },
    ],
    stages: [
      {
        id: "make-colloid",
        title: "Make one cloudy sample",
        goal: "Add milk water and look for a cloudy but even mixture.",
        materialIds: ["testTube"],
        toolIds: ["add-milk"],
        requiredEvidence: ["cloudy-colloid"],
        nextPrompt: "Start with milk water. Watch if the sample stays evenly cloudy.",
      },
      {
        id: "test-light",
        title: "Test with light",
        goal: "Shine light through the cloudy sample.",
        materialIds: ["testTube"],
        toolIds: ["light"],
        requiredEvidence: ["tyndall-visible"],
        nextPrompt: "Now use light. Does the beam become visible?",
      },
      {
        id: "test-chalk",
        title: "Try a solid mixture",
        goal: "Make chalk water and see if the solid settles.",
        materialIds: ["testTube"],
        toolIds: ["add-chalk", "wait"],
        requiredEvidence: ["chalk-suspension", "chalk-settles"],
        nextPrompt: "Add chalk water, then wait. Large particles may sink.",
      },
      {
        id: "filter-chalk",
        title: "Catch the solid",
        goal: "Use the filter to test if the chalk can be trapped.",
        materialIds: ["testTube"],
        toolIds: ["filter"],
        requiredEvidence: ["chalk-residue"],
        nextPrompt: "Filter the chalk water. Look for solid caught on the filter.",
      },
    ],
    conclusions: [
      {
        id: "colloid-suspension",
        label: "Colloids scatter light; suspensions settle and can be filtered.",
        correct: true,
        requiresEvidence: ["tyndall-visible", "chalk-settles", "chalk-residue"],
        feedback: "Yes. Milk water scatters light. Chalk water settles and the filter catches the chalk.",
      },
      {
        id: "all-same",
        label: "All cloudy mixtures behave the same way.",
        correct: false,
        requiresEvidence: ["tyndall-visible", "chalk-settles"],
        feedback: "Not quite. The tests showed different changes, so the cloudy mixtures are not all the same.",
      },
    ],
    notebook: {
      goal: "Use small tests to compare cloudy mixtures.",
      hints: ["Look at what changes first.", "Use the science words after the observation makes sense."],
      explanation:
        "Colloids keep fine particles spread out and scatter light. Suspensions have larger particles that can settle and be trapped by a filter.",
    },
    stationVisuals: missionPresentations[0].stationVisuals,
    completionMessage:
      "You classified cloudy mixtures by collecting evidence from tools, not guesses.",
  },
  {
    scenarioId: "salt-sand",
    badge: "Dissolve + separate",
    question: "How can we get sand and salt apart?",
    materials: [
      { id: "beaker", label: "Salt + sand beaker", stationId: "beaker" },
      { id: "filtrate", label: "Salt water filtrate", stationId: "filtrate" },
    ],
    tools: [
      { id: "add-water", label: "Water", action: { type: "pour", reagent: "water" } },
      { id: "wait", label: "Wait", action: { type: "wait" } },
      { id: "filter", label: "Filter", action: { type: "filter" } },
      { id: "heat", label: "Heat", action: { type: "heat" } },
    ],
    interactions: [
      {
        id: "water-dissolves-salt",
        materialId: "beaker",
        toolId: "add-water",
        evidenceId: "salt-dissolves",
        feedbackCard: feedbackCard(
          "You added water to the salt and sand.",
          "Salt mixes into the water. Sand stays as solid grains.",
          "Water changes the salt but not the sand.",
          "Now filter the wet mixture to catch the sand.",
          "Water dissolves salt. Sand does not dissolve.",
        ),
        soundCue: "pour",
        reactionEffect: "dissolve",
        observation: "Salt mixes into the water. Sand still looks like solid grains.",
        explanation: "Salt dissolves in water. Sand does not dissolve.",
        effectTags: ["settle-particles"],
      },
      {
        id: "wait-is-not-enough",
        materialId: "beaker",
        toolId: "wait",
        evidenceId: "waiting-not-enough",
        feedbackCard: feedbackCard(
          "You waited without changing the mixture.",
          "The salt and sand are still together.",
          "Waiting alone does not use a property difference.",
          "Try water so one part of the mixture changes.",
          "Waiting alone does not separate salt and sand.",
        ),
        soundCue: "wait",
        reactionEffect: "settle",
        observation: "Waiting lets grains rest, but salt is still mixed with the water.",
        explanation: "This is useful evidence. Waiting alone does not solve the problem.",
        effectTags: ["settle-particles"],
      },
      {
        id: "filter-sand",
        materialId: "beaker",
        toolId: "filter",
        evidenceId: "sand-residue",
        feedbackCard: feedbackCard(
          "You filtered the wet mixture.",
          "The filter catches sand. Salt water goes through.",
          "The sand is an insoluble solid, so the filter can trap it.",
          "Heat the salt water to recover the salt.",
          "Filtration catches sand while salt water passes through.",
        ),
        soundCue: "filter",
        reactionEffect: "filter-residue",
        observation: "The filter catches sand. Salt water goes through.",
        explanation: "This is filtration: an insoluble solid is trapped by the filter.",
        effectTags: ["trap-residue"],
      },
      {
        id: "heat-filtrate",
        materialId: "filtrate",
        toolId: "heat",
        evidenceId: "salt-crystals",
        feedbackCard: feedbackCard(
          "You heated the salt water.",
          "Water leaves as vapour. Salt crystals stay behind.",
          "Heat removes the water but does not remove the salt.",
          "Use all three pieces of evidence to choose a conclusion.",
          "Heating salt water leaves salt crystals behind.",
        ),
        soundCue: "heat",
        reactionEffect: "vapour",
        observation: "Water leaves as vapour. Salt crystals stay behind.",
        explanation: "This is evaporation. The solvent leaves and the dissolved solid remains.",
        effectTags: ["distil-vapour", "gas-up-arrow"],
        gasLabel: "H2O↑",
      },
    ],
    stages: [
      {
        id: "dissolve",
        title: "Make one solid dissolve",
        goal: "Add water and notice which solid changes.",
        materialIds: ["beaker"],
        toolIds: ["add-water", "wait"],
        requiredEvidence: ["salt-dissolves"],
        nextPrompt: "Try water. Salt and sand do not behave the same way in water.",
      },
      {
        id: "filter",
        title: "Remove the sand",
        goal: "Filter the wet mixture to catch sand.",
        materialIds: ["beaker"],
        toolIds: ["filter"],
        requiredEvidence: ["sand-residue"],
        nextPrompt: "Now use the filter. Look for what gets caught.",
      },
      {
        id: "recover-salt",
        title: "Get salt back",
        goal: "Heat the salt water and watch what is left.",
        materialIds: ["filtrate"],
        toolIds: ["heat"],
        requiredEvidence: ["salt-crystals"],
        nextPrompt: "Heat the liquid that passed through the filter.",
      },
    ],
    conclusions: [
      {
        id: "separate-salt-sand",
        label: "Dissolve salt, filter sand, then evaporate water.",
        correct: true,
        requiresEvidence: ["salt-dissolves", "sand-residue", "salt-crystals"],
        feedback: "Yes. Water dissolves salt, the filter catches sand, and heat removes water.",
      },
      {
        id: "wait-only",
        label: "Waiting alone separates the full mixture.",
        correct: false,
        requiresEvidence: ["waiting-not-enough"],
        feedback: "Waiting showed a non-result. You still need water, filtering, and heating.",
      },
    ],
    notebook: {
      goal: "Separate both parts of a salt and sand mixture.",
      hints: ["Ask what changes after each tool.", "Heat the filtrate after the sand is removed."],
      explanation:
        "Salt dissolves in water, sand does not, and evaporation removes water from the salt solution.",
    },
    stationVisuals: missionPresentations[1].stationVisuals,
    completionMessage: "You separated salt and sand through evidence-driven choices.",
  },
  {
    scenarioId: "crystallization",
    badge: "Crystal growth",
    question: "How can we grow cleaner crystals from a dirty solid?",
    materials: [
      { id: "dish", label: "Impure blue solution", stationId: "dish" },
      { id: "filtrate", label: "Clean filtrate", stationId: "filtrate" },
    ],
    tools: [
      { id: "add-water", label: "Water", action: { type: "pour", reagent: "water" } },
      { id: "heat", label: "Heat", action: { type: "heat" } },
      { id: "filter", label: "Filter", action: { type: "filter" } },
      { id: "cool", label: "Cool", action: { type: "cool" } },
    ],
    interactions: [
      {
        id: "make-solution",
        materialId: "dish",
        toolId: "add-water",
        evidenceId: "blue-solution",
        feedbackCard: feedbackCard(
          "You added water to the impure blue solid.",
          "The useful blue solid colours the water. Dust is still visible.",
          "Water dissolves the blue solid but not the dust.",
          "Warm the solution so it can hold more dissolved solid.",
          "Water dissolves the blue solid, but dust remains.",
        ),
        soundCue: "pour",
        reactionEffect: "dissolve",
        observation: "The blue solid colours the water. Dust is still visible.",
        explanation: "The useful solid dissolves, but the dust does not.",
      },
      {
        id: "heat-solution",
        materialId: "dish",
        toolId: "heat",
        evidenceId: "hot-solution",
        feedbackCard: feedbackCard(
          "You heated the blue solution.",
          "The solution becomes hotter and deeper blue.",
          "A hot solution can hold more dissolved solid.",
          "Filter out the dust before crystals grow.",
          "Heating helps make a stronger blue solution.",
        ),
        soundCue: "heat",
        reactionEffect: "heat",
        observation: "The blue solution gets hot and deeper in colour.",
        explanation: "A hot solution can hold more dissolved solid.",
        effectTags: ["distil-vapour"],
      },
      {
        id: "filter-dust",
        materialId: "dish",
        toolId: "filter",
        evidenceId: "dust-removed",
        feedbackCard: feedbackCard(
          "You filtered the hot blue solution.",
          "Dust stays on the filter. Blue liquid passes through.",
          "The dust is insoluble, so the filter can remove it.",
          "Cool the clean blue liquid to grow crystals.",
          "Filtering removes insoluble dust from the blue solution.",
        ),
        soundCue: "filter",
        reactionEffect: "filter-residue",
        observation: "Dust stays on the filter. Blue liquid goes through.",
        explanation: "Filtering removes the insoluble dirt before crystals grow.",
        effectTags: ["trap-residue"],
      },
      {
        id: "cool-crystals",
        materialId: "filtrate",
        toolId: "cool",
        evidenceId: "crystals-grown",
        feedbackCard: feedbackCard(
          "You cooled the clean blue liquid.",
          "Blue crystals appear.",
          "Cooling makes some dissolved solid come back out as crystals.",
          "Use the evidence to choose the crystal method.",
          "Cooling a clean solution can grow crystals.",
        ),
        soundCue: "cool",
        reactionEffect: "crystals",
        observation: "Blue crystals appear as the clean liquid cools.",
        explanation: "This is crystallization. Cooling makes some dissolved solid come out as crystals.",
        effectTags: ["grow-crystals"],
      },
    ],
    stages: [
      {
        id: "make-hot-solution",
        title: "Make a hot solution",
        goal: "Use water and heat so the blue solid dissolves.",
        materialIds: ["dish"],
        toolIds: ["add-water", "heat"],
        requiredEvidence: ["blue-solution", "hot-solution"],
        nextPrompt: "Make the solid dissolve, then warm the solution.",
      },
      {
        id: "remove-dust",
        title: "Clean the liquid",
        goal: "Filter out the dust before crystals form.",
        materialIds: ["dish"],
        toolIds: ["filter"],
        requiredEvidence: ["dust-removed"],
        nextPrompt: "Use the filter to remove dirt from the hot solution.",
      },
      {
        id: "grow-crystals",
        title: "Cool the clean liquid",
        goal: "Cool the filtrate and look for crystals.",
        materialIds: ["filtrate"],
        toolIds: ["cool"],
        requiredEvidence: ["crystals-grown"],
        nextPrompt: "Now cool the clean blue liquid.",
      },
    ],
    conclusions: [
      {
        id: "crystal-method",
        label: "Make a hot clean solution, then cool it to grow crystals.",
        correct: true,
        requiresEvidence: ["blue-solution", "hot-solution", "dust-removed", "crystals-grown"],
        feedback: "Yes. First dissolve, then clean the liquid, then cool it so crystals form.",
      },
      {
        id: "filter-crystals-first",
        label: "Filter first to collect copper sulfate crystals.",
        correct: false,
        requiresEvidence: ["blue-solution", "dust-removed"],
        feedback: "Filtering removes insoluble dust, but dissolved copper sulfate crystallizes after cooling.",
      },
    ],
    notebook: {
      goal: "Grow crystals after removing dirt.",
      hints: ["Make a solution before filtering.", "Cool the clean filtrate, not the dirty dish."],
      explanation:
        "Crystallization uses solubility changing with temperature: the hot solution holds more solute, then cooling forms crystals.",
    },
    stationVisuals: missionPresentations[2].stationVisuals,
    completionMessage: "You grew crystals from a cleaned hot solution.",
  },
  {
    scenarioId: "distillation",
    badge: "Boiling points",
    question: "How can we separate two liquids mixed together?",
    materials: [
      { id: "flask", label: "Acetone + water flask", stationId: "flask" },
    ],
    tools: [
      { id: "heat", label: "Heat", action: { type: "heat" } },
      { id: "filter", label: "Filter", action: { type: "filter" } },
      { id: "cool", label: "Cool", action: { type: "cool" } },
    ],
    interactions: [
      {
        id: "filter-does-not-work",
        materialId: "flask",
        toolId: "filter",
        evidenceId: "filter-not-for-liquids",
        feedbackCard: feedbackCard(
          "You tried to filter the liquid mixture.",
          "The filter does not separate the two liquids.",
          "A filter catches solids, but this mixture has two liquids.",
          "Try heating to make one liquid leave first.",
          "Filtering does not separate acetone and water.",
        ),
        soundCue: "wrong-tool",
        reactionEffect: "filter-residue",
        observation: "The filter does not separate two liquids mixed together.",
        explanation: "Filtering needs a solid to catch. These are both liquids.",
      },
      {
        id: "distil-acetone",
        materialId: "flask",
        toolId: "heat",
        evidenceId: "acetone-first",
        feedbackCard: feedbackCard(
          "You heated the liquid mixture.",
          "One liquid boils first and is collected.",
          "The lower-boiling liquid turns to vapour first.",
          "Keep heating to recover the remaining liquid.",
          "The lower-boiling liquid distils first.",
        ),
        soundCue: "heat",
        reactionEffect: "vapour",
        observation: "One liquid boils first and is collected in the first receiver.",
        explanation: "The lower-boiling liquid changes to vapour first, then condenses.",
        effectTags: ["distil-vapour", "gas-up-arrow"],
        gasLabel: "acetone↑",
      },
      {
        id: "distil-water",
        materialId: "flask",
        toolId: "heat",
        evidenceId: "water-second",
        feedbackCard: feedbackCard(
          "You kept heating the flask.",
          "The remaining water vapour is collected next.",
          "The higher-boiling liquid comes later.",
          "Use both collected liquids to choose a conclusion.",
          "Continued heating recovers the higher-boiling liquid.",
        ),
        soundCue: "heat",
        reactionEffect: "vapour",
        observation: "More heating sends the remaining water vapour to the next receiver.",
        explanation: "The higher-boiling liquid comes later.",
        effectTags: ["distil-vapour", "gas-up-arrow"],
        gasLabel: "H2O↑",
      },
    ],
    stages: [
      {
        id: "reject-filter",
        title: "Test the obvious tool",
        goal: "Try filtering and see why it is not enough.",
        materialIds: ["flask"],
        toolIds: ["filter", "heat"],
        requiredEvidence: ["filter-not-for-liquids"],
        nextPrompt: "A filter catches solids. Try it once, then choose a better idea.",
      },
      {
        id: "first-liquid",
        title: "Boil one liquid first",
        goal: "Heat the flask and collect the first vapour.",
        materialIds: ["flask"],
        toolIds: ["heat"],
        requiredEvidence: ["acetone-first"],
        nextPrompt: "Heat the mixture. Watch which liquid leaves first.",
      },
      {
        id: "second-liquid",
        title: "Recover the rest",
        goal: "Keep heating to collect the remaining liquid.",
        materialIds: ["flask"],
        toolIds: ["heat"],
        requiredEvidence: ["water-second"],
        nextPrompt: "Heat again. The liquid with the higher boiling point comes later.",
      },
    ],
    conclusions: [
      {
        id: "boiling-points",
        label: "The lower-boiling liquid distils first, then the remaining liquid.",
        correct: true,
        requiresEvidence: ["acetone-first", "water-second"],
        feedback: "Yes. Heating used boiling point differences to collect the liquids one after another.",
      },
      {
        id: "filter-liquids",
        label: "A filter separates acetone and water.",
        correct: false,
        requiresEvidence: ["filter-not-for-liquids"],
        feedback: "That evidence shows why filtration is not the right method here.",
      },
    ],
    notebook: {
      goal: "Recover both liquids from one liquid mixture.",
      hints: ["Filtering is useful evidence, but not the solution.", "Heating more than once can collect more than one liquid."],
      explanation:
        "Acetone has a lower boiling point than water, so it vaporizes and condenses first.",
    },
    stationVisuals: missionPresentations[3].stationVisuals,
    completionMessage: "You recovered both liquids by their boiling points.",
  },
  {
    scenarioId: "chromatography",
    badge: "Hidden pigments",
    question: "How can we see the colours hidden in black ink?",
    materials: [{ id: "paper", label: "Chromatography paper", stationId: "paper" }],
    tools: [
      { id: "ink", label: "Ink spot", action: { type: "pour", reagent: "black-ink" } },
      { id: "water", label: "Water", action: { type: "pour", reagent: "water" } },
      { id: "run", label: "Run", action: { type: "chromatograph" } },
      { id: "heat", label: "Heat", action: { type: "heat" } },
    ],
    interactions: [
      {
        id: "spot-ink",
        materialId: "paper",
        toolId: "ink",
        evidenceId: "ink-spot",
        feedbackCard: feedbackCard(
          "You placed black ink on the paper.",
          "A small dark spot sits near the bottom.",
          "A small starting spot lets the colours separate clearly.",
          "Add water so the solvent can move through the paper.",
          "Chromatography starts with one small ink spot.",
        ),
        soundCue: "pour",
        reactionEffect: "dissolve",
        observation: "A dark ink spot sits near the bottom of the paper.",
        explanation: "The colours are still mixed inside the spot.",
      },
      {
        id: "add-solvent",
        materialId: "paper",
        toolId: "water",
        evidenceId: "solvent-added",
        feedbackCard: feedbackCard(
          "You added water to the paper.",
          "Water begins moving upward.",
          "The moving liquid can carry ink pigments with it.",
          "Run the paper and watch the colours separate.",
          "The solvent moves through the paper.",
        ),
        soundCue: "pour",
        reactionEffect: "dissolve",
        observation: "Water touches the paper and starts moving upward.",
        explanation: "The moving liquid is the solvent.",
      },
      {
        id: "run-chromatography",
        materialId: "paper",
        toolId: "run",
        evidenceId: "pigment-bands",
        feedbackCard: feedbackCard(
          "You let the solvent move through the ink.",
          "The black spot separates into coloured bands.",
          "Different pigments travel different distances.",
          "Use the bands as evidence for the conclusion.",
          "Chromatography separates pigments into bands.",
        ),
        soundCue: "chromatograph",
        reactionEffect: "chromatography-bands",
        observation: "The black spot separates into coloured bands.",
        explanation: "This is chromatography. Different colours travel different distances.",
        effectTags: ["chromatography-bands"],
      },
      {
        id: "heat-paper",
        materialId: "paper",
        toolId: "heat",
        evidenceId: "heat-not-method",
        feedbackCard: feedbackCard(
          "You heated the paper.",
          "The paper dries, but neat colour bands do not form.",
          "Heat does not carry pigments through the paper.",
          "Use solvent movement instead.",
          "Heating does not separate ink into bands.",
        ),
        soundCue: "wrong-tool",
        reactionEffect: "heat",
        observation: "Heating dries the paper but does not make neat colour bands.",
        explanation: "This non-result shows that movement of solvent is the important part.",
      },
    ],
    stages: [
      {
        id: "spot",
        title: "Place the ink",
        goal: "Put one ink spot on the paper.",
        materialIds: ["paper"],
        toolIds: ["ink", "heat"],
        requiredEvidence: ["ink-spot"],
        nextPrompt: "Start with an ink spot near the bottom of the paper.",
      },
      {
        id: "solvent",
        title: "Let water move",
        goal: "Add water so it can carry the ink.",
        materialIds: ["paper"],
        toolIds: ["water"],
        requiredEvidence: ["solvent-added"],
        nextPrompt: "Add a small amount of water. Watch it climb the paper.",
      },
      {
        id: "bands",
        title: "Reveal the bands",
        goal: "Run the paper and look for separated colours.",
        materialIds: ["paper"],
        toolIds: ["run"],
        requiredEvidence: ["pigment-bands"],
        nextPrompt: "Let the solvent carry the pigments.",
      },
    ],
    conclusions: [
      {
        id: "pigments-travel",
        label: "Solvent carries pigments different distances through paper.",
        correct: true,
        requiresEvidence: ["ink-spot", "solvent-added", "pigment-bands"],
        feedback: "Correct. Different pigments travel at different speeds and separate into bands.",
      },
      {
        id: "heat-ink",
        label: "Heat separates ink colours.",
        correct: false,
        requiresEvidence: ["heat-not-method"],
        feedback: "Heating gave a useful non-result. Solvent movement made the bands.",
      },
    ],
    notebook: {
      goal: "Reveal colours hidden inside black ink.",
      hints: ["Add ink and solvent before running the paper.", "The solvent front does the separating."],
      explanation:
        "Chromatography separates soluble pigments because they travel different distances with the solvent.",
    },
    stationVisuals: missionPresentations[4].stationVisuals,
    completionMessage: "You separated ink into pigment bands.",
  },
];

export const sandboxLabMissions: readonly SandboxLabMission[] = missions.map(
  (scenario, index) => ({
    scenario,
    presentation: sandboxMissionPresentations[index],
  }),
);
