import type { StorySceneDefinition } from "../contracts/story";

export const introScene: StorySceneDefinition = {
  id: "storm-intro",
  beats: [
    {
      id: "storm-strikes",
      speaker: "narrator",
      textKey: "intro.narrator.stormStrikes",
      text: "Rain lashes the school field station. Then every light snaps off.",
      backgroundId: "field-station-blackout",
      backgroundState: "lightning",
      portraitPosition: "left",
      messageBoxVariant: "urgent",
      audioCue: "thunder",
      transition: "fade",
      next: "mira-checks-in",
    },
    {
      id: "mira-checks-in",
      speaker: "mira",
      expression: "worried",
      textKey: "intro.mira.checksIn",
      text: "Kabir? You okay? I can't see the workbench.",
      backgroundId: "field-station-blackout",
      backgroundState: "blackout",
      portraitPosition: "left",
      messageBoxVariant: "standard",
      transition: "cut",
      next: "kabir-finds-torch",
    },
    {
      id: "kabir-finds-torch",
      speaker: "kabir",
      expression: "thinking",
      textKey: "intro.kabir.findsTorch",
      text: "I'm here. The emergency torch should work, but it is dark too.",
      backgroundId: "field-station-blackout",
      backgroundState: "storm",
      portraitPosition: "right",
      messageBoxVariant: "standard",
      transition: "cut",
      next: "rao-radio",
    },
    {
      id: "rao-radio",
      speaker: "ms-rao",
      textKey: "intro.rao.radio",
      text: "Mira, Kabir... stay inside. Restore the low-voltage emergency systems. I'll meet you by the server room.",
      backgroundId: "field-station-blackout",
      backgroundState: "storm",
      portraitPosition: "radio",
      messageBoxVariant: "radio",
      audioCue: "radio-static",
      transition: "cut",
      next: "mira-plan",
    },
    {
      id: "mira-plan",
      speaker: "mira",
      expression: "excited",
      textKey: "intro.mira.plan",
      text: "First the torch. If we can see the bench, we can find the hall controls.",
      backgroundId: "field-station-blackout",
      backgroundState: "blackout",
      portraitPosition: "left",
      messageBoxVariant: "standard",
      transition: "cut",
      next: "kabir-caution",
    },
    {
      id: "kabir-caution",
      speaker: "kabir",
      expression: "worried",
      textKey: "intro.kabir.caution",
      text: "Slowly. We arrange the parts first, then press Test.",
      backgroundId: "field-station-blackout",
      backgroundState: "storm",
      portraitPosition: "right",
      messageBoxVariant: "standard",
      transition: "fade",
      next: "repair",
    },
  ],
};
